In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [2]:
def comb(n):
    a = np.arange(n)

    # 通过meshgrid生成二维矩阵，每一行都是一维数组a的一个副本
    rows, cols = np.meshgrid(a, a)

    # 使用布尔索引来筛选组合，只保留满足要求的
    mask = np.logical_and(rows < cols, cols < n)
    comb = np.column_stack((rows[mask], cols[mask]))
    return len(comb)

Example
=

In [3]:
l_2 = [[0, 0], [1, 0], [0, 1], [2, 0], [1, 1], [0, 2]]
l_3 = [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1], [0, 2, 0], [0, 1, 1], [0, 0, 2]]

In [4]:
print(comb(2+2))

6


In [5]:
n_feature = 3
n_sample = 2

arr2 = np.array(l_2)
arr3 = np.array(l_3)
x_22 = np.arange(1, n_feature * n_sample + 1).reshape(n_sample, -1)

output = np.zeros((n_sample, comb(n_feature+2)))

print(PolynomialFeatures(degree=2).fit_transform(x_22))
def multiply_arrays(X, arr):
    n_sample, n_feature = X.shape
    output = np.zeros((n_sample, comb(n_feature+2)))
    for i in range(comb(n_feature + 2)):
        for f in range(n_sample):
            x = X[f,:]
            w = arr[i,:]
            output[f, i] = np.prod(np.power(x,w))
    return output
multiply_arrays(x_22, arr3)

[[ 1.  1.  2.  3.  1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5.  6. 16. 20. 24. 25. 30. 36.]]


array([[ 1.,  1.,  2.,  3.,  1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5.,  6., 16., 20., 24., 25., 30., 36.]])

In [22]:
def generate_combinations(n, b):
    combinations = []

    # 定義遞迴函數來生成所有可能的球的配置方式
    def generate_helper(current_combination, balls, baskets):
        if basket == n:
            combinations.append(current_combination) # 裝滿了 跳下一個排列
            return
        if ball == b:
            generate_combinations


    # 呼叫遞迴函數來生成所有可能的組合
    generate_helper([], b, n)

    return combinations


# 測試程式碼
n = 3
b = 2
combinations = generate_combinations(n, b)

n = 3, b = 2
i = 0, combinations = [], remain_ball = 2, remain_basket = 3
i = 0, combinations = [0], remain_ball = 2, remain_basket = 2
i = 0, combinations = [0, 0], remain_ball = 2, remain_basket = 1
[[0, 0, 0]]

i = 1, combinations = [0, 0], remain_ball = 2, remain_basket = 1
[[0, 0, 0], [1, 0, 0]]

i = 2, combinations = [0, 0], remain_ball = 2, remain_basket = 1
[[0, 0, 0], [1, 0, 0], [2, 0, 0]]

i = 1, combinations = [0], remain_ball = 2, remain_basket = 2
i = 0, combinations = [1, 0], remain_ball = 1, remain_basket = 1
[[0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0]]

i = 1, combinations = [1, 0], remain_ball = 1, remain_basket = 1
[[0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [1, 1, 0]]

i = 2, combinations = [0], remain_ball = 2, remain_basket = 2
[[0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [1, 1, 0], [0, 2, 0]]

i = 1, combinations = [], remain_ball = 2, remain_basket = 3
i = 0, combinations = [1], remain_ball = 1, remain_basket = 2
i = 0, combinations = [0, 1], remain_ball = 1, re

In [29]:
def generate_combinations(n, b):
    combinations = []
    print(f'n = {n}, b = {b}')

    # 定義遞迴函數來生成所有可能的球的配置方式
    def generate_helper(current_combination, remaining_balls, remaining_baskets):
        if remaining_baskets == 0:
            combinations.append(current_combination)
            #print(combinations, end = "\n\n")
            return
        if remaining_balls == 0:
            generate_helper([0] + current_combination, 0, remaining_baskets - 1)
            return
        for i in range(remaining_balls + 1):
            #print(f'i = {i}, combinations = {current_combination}, remain_ball = {remaining_balls}, remain_basket = {remaining_baskets}')
            generate_helper([i] + current_combination, remaining_balls - i, remaining_baskets - 1)

    # 呼叫遞迴函數來生成所有可能的組合
    generate_helper([], b, n)

    return combinations


# 測試程式碼
n = 3
b = 2
combinations = generate_combinations(n, b)
print(combinations)
print(f'answer = \n{l_3}')

n = 3, b = 2
[[0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 1, 0], [1, 1, 0], [0, 2, 0], [0, 0, 1], [1, 0, 1], [0, 1, 1], [0, 0, 2]]
answer = 
[[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1], [0, 2, 0], [0, 1, 1], [0, 0, 2]]


In [25]:
print(combinations(3, 1))

TypeError: 'list' object is not callable